{
:date "2017-09-18"
:title "Busy (Clojure) Developer Guide to Podcasts"
:layout :post
:tags  ["clojure" "podcast" "learning"]
}

:toc:

_In this post, I'll share with you the list of my favorite podcasts.
Some of them are focusing on Clojure, but others are more general.
This is just a very brief summary.
In the future, I'd like to write more posts highlighting my favorite episodes._

In the fast-pacing technology world, it's very hard to stay up to date and very easy to get overwhelmed with the number of new articles, blog posts, conference talks, frameworks.
A podcast is an attractive medium and can be a great supplement to other learning resources.

What follows is the list of the podcasts I listen to on a regular basis.

== 1. Cognicast

This is my favorite (mostly) Clojure podcast by Cognitect, and it should be on the radar of every serious Clojure developer.

It's maintained by authors of Clojure.
The quality of episodes stays high, and they are rich sources of information.

In the past, it was hosted by https://twitter.com/craigandera[Craig Andera].
Since Craig left Cognitect, the podcast has gotten three new hosts: https://twitter.com/timbaldridge[Timothy Baldridge], https://twitter.com/gigasquid[Carin Meier], and https://twitter.com/stuartsierra[Stuart Sierra].

They cover a variety of topics, and the podcast has an unusual format:

* They always start by asking a guest to share an interesting experience of art whatever it means to the guest.
* They always end by asking a guest to share a piece of advice

You can find the list of all episodes with show notes and full transcription (starting with episode 94) at http://blog.cognitect.com/cognicast/.

== 2. Software Engineering Radio

This is my favorite general SW engineering podcast.

It covers lots of topics, and unlike https://softwareengineeringdaily.com/[Software Engineering Daily] comes with new episodes at a reasonable pace (every two weeks or so).
The topics include software development, testing, social aspects like communication and leading teams, distributed systems, performance, clean code, and more.

There are even some episodes covering Clojure, e.g.
http://www.se-radio.net/2016/05/se-radio-episode-257-michael-nygard-on-clojure-in-practice/[Episode 257: Michael Nygard on Clojure in Practice] or http://www.se-radio.net/2010/03/episode-158-rich-hickey-on-clojure/[Episode 158: Rich Hickey on Clojure].

You can find the list of episodes with brief summaries at http://www.se-radio.net/.

== 3. Defn.audio

This is an alternative and fun Clojure-only podcast hosted by Vijay Kiran and Ray McDermot from Holland and Belgium.
Unlike most of other podcasts, it has two hosts, and there's a ton of humor in each episode :).

They interview very interesting people from Clojure community: the list of former hosts include https://defn.audio/2016/10/06/episode-11-alex-miller/[Alex Miller], https://defn.audio/2017/05/11/episode-21-james-reeves-aka-weavejester/[James Reeves], and https://defn.audio/2017/06/26/episode-23-the-right-honourable-mr-stuart-halloway-aka-stuarthalloway/[Stuart Halloway].

Again, the list of all episodes with short summaries is available online at https://defn.audio/.

== 4. Functional Geekery

Unlike Cognicast or Defn Podcast, this podcast doesn't focus on any particular programming language.
Its topic is functional programming in general, and it's a good supplement to Clojure centric podcasts.

The podcast's host https://www.proctor-it.com/[Proctor] asks very interesting questions and people like this podcast quite a lot.

Usually, there's a comprehensive list of links for each episode at https://www.functionalgeekery.com/.

== 5. CaSE: Conversations about Software Engineering

I discovered this podcast only recently, after attending EuroClojure 2017 when they recorded the http://www.case-podcast.org/8-clojure-with-alex-miller[episode with Alex Miller].
They cover a full range of topics including Software architecture, Microservices, or Legacy Software.

http://www.case-podcast.org/[There are only ten episodes so far], so now it's a good time to start listening and catch up on previous episodes.

== How to stay up to date

Usually, I listen to podcasts during the morning walk with my dog.
That means I can finish three podcasts a week on average.
Alternating between mostly Clojure (Cognicast and Defn) and more general (Software Engineering Radio, CaSE, and Functional Geekery) gives me a wide variety of topics and broadens my horizons.

If you're just starting with podcasts, I suggest picking only one or two.
As you already know, I recommend the combo _Cognicast + Software Engineering Radio_.

== Call for Action

Now it's your turn.
Take your time to pick a favorite podcast or two and start listening tomorrow!

== Future Posts: Podcasts Summaries

In the future posts, I'd like to write the reviews of the podcasts' episodes that I liked with brief notes for each episode.

Stay tuned!
