{
:date "2023-09-15"
:title "Git - How to Delete Merged Branches Older than X Days?"
:layout :post
:tags  ["git" "command-line" "bash" "awk"]
}

:toc:

At https://codescene.com/[CodeScene^], we used to not delete merged git branches, at all.
The practice came  from https://codescene.io/docs/guides/branches/branch-analyses.html[Branch Analysis^].
To get that data, we didn't want to remove a merged branch immediately.
However, we ended up, _never_ deleting them which also causes a problem: over time you accumulate _thousands_ of branches.
That creates a mess and makes it hard (or impossible) to select proper branch in CodeScene itself
(the max number of branches we load and display is 1000).

Recently, we decided that it's time to start removing _older_ merged branches
We still want to keep _recent_ merged branches for ocassional review (via CodeScene's branch analyses)
but we do not need anything older than 1 month.

The question arises, how to do it:
There's setting in GitHub to do this automatically
(see https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches[Managing the automatic deletion of branches^]).
But that's pretty much instantaneous - it deletes the merged branch immediately, which isn't what we want.

So we have to resort to a more manual approach - we decided to write a script that's periodically run via GitHub Actions.

## Ok, can you tell me how to actually do it?

### TL;DR: The final script

It's quite simple - I ended up writing this "one-liner"footnote:[I know, it's more than one line but that's just definition of a couple of environment variables]:

[source,bash]
----
MAIN_BRANCH=master
MAX_AGE_DAYS=30
git branch -r --merged origin/${MAIN_BRANCH} --no-contains ${MAIN_BRANCH} --format='%(committerdate:raw)%09%(refname:short)' | awk -v max_age=$(( $MAX_AGE_DAYS * 86400 )) -v now=$(date +%s) '{ diff = now - $1; if (diff > max_age) print $3 }' | sed 's/origin\///' | xargs git push --delete origin
----

### How it works

It works like this:

1. Find all the branches merged into the main branch (excluding the main)
+
[source,bash]
----
git branch -r --merged origin/${MAIN_BRANCH} --no-contains ${MAIN_BRANCH} ...
----
2. ... while adding `committerdate`  at the same time - using the `raw` format to get Unix Epoch seconds:
+
[source,bash]
----
... --format='%(committerdate:raw)%09%(refname:short)' 
----
3. Use `awk` to calculate the difference between current time and print branch names only for refs with commiterdate older than the threshold (30 days)
+
[source,bash]
----
awk -v max_age=$(( $MAX_AGE_DAYS * 86400 )) -v now=$(date +%s) '{ diff = now - $1; if (diff > max_age) print $3 }'
----
Notice how I use https://stackoverflow.com/questions/19075671/how-do-i-use-shell-variables-in-an-awk-script[`awk -v` to define _awk_ variables^] `max_age` and `now` because I cannot reference shell variables easily inside the awk script
4. Remove the 'origin/' prefix
+
[source,bash]
----
sed 's/origin\///'
----
5. Finally, delete all the matching branches
+
[source,bash]
----
xargs git push --delete origin
----

The output of the first two steps may look like this:

[source,bash]
----
1683723780 +0200        origin/branch-a
1683190390 +0200        origin/branch-b
----


## GitHub Actions job

Running this via GH Actions is relatively easy, but there's one critical piece you need to be aware of
- the checkout step has be configured with `fetch-depth: 0` footnote:[Thanks, Kalle!]:

[source]
----
...
      - uses: actions/checkout@v3
        with:
          # Fetch all the branches to be able to list them later
          fetch-depth: 0
----

Otherwise, the script won't be able to find anything and fails with a rather cryptic error:
"fatal: --delete doesn't make sense without any refs"

### Full job definition

[source,yaml]
----
name: Delete old merged git branches
on:
  schedule:
    - cron: "0 6 * * 1-5"
  workflow_dispatch:
    inputs:
      max-age-days:
        description: "Branches older than 'age' (days) will be deleted. Default: 30"
        required: true
        default: 30
        type: number
      main-branch:
        description: "The main branch that shouldn't be deleted. Default: 'master'"
        required: true
        default: master
        type: string

env:
  MAX_AGE_DAYS: ${{ github.event.inputs.max-age-days }}
  MAIN_BRANCH: ${{ github.event.inputs.main-branch }}

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: "Print info"
        run: echo "The script will remove all git branches older than ${{ env.MAX_AGE_DAYS }} days and merged into the ${{ env.MAIN_BRANCH }} branch."
      - uses: actions/checkout@v3
        with:
          # Fetch all the branches to be able to list them later
          fetch-depth: 0
      - name: "Delete old merged branches"
      # The best way to understand this is to actually run it piece-by-piece, perhaps skipping the last command (actual delete)
      # ----
      # 1. The "git branch" command shows all the merged branches with the date (unix epoch seconds) of the latest commit, e.g.
      #        1636550813 +0100        origin/1095-improve-trello-provider
      # 2. The "awk" command filter out those that are older then the threshold, printing only the branch names ($3)
      # 3. Finally, we delete the branches one by one via `xargs git push --delete ...`
      # ----
      # NOTE:  the 'origin/' prefix for the branch name is needed later, otherwise it fails on GH actions with this error: "fatal: --delete doesn't make sense without any refs"
        run: git branch -r --merged origin/${{ env.MAIN_BRANCH }} --no-contains origin/${{ env.MAIN_BRANCH }} --format='%(committerdate:raw)%09%(refname:short)' | awk -v max_age=$(( ${{ env.MAX_AGE_DAYS }} * 86400 )) -v now=$(date +%s) '{ diff = now - $1; if (diff > max_age) print $3 }' | sed 's/origin\///' | xargs git push --delete origin

----


## References

* https://codescene.io/docs/guides/branches/branch-analyses.html[CodeScene's Branch Analysis^]
* https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches[GitHub - Managing the automatic deletion of branches^]
* https://stackoverflow.com/questions/19075671/how-do-i-use-shell-variables-in-an-awk-script[use `awk -v` to define an _awk_ variable^] 